---
name: Molecule CI
on:
  pull_request:
  push:

jobs:

  cache-dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Cache pip installed packages.
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install test dependencies.
        run: pip install -r pip/requirements.txt

  test:
    needs: cache-dependencies
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        playbookdistro:
          - fedora:36
          - quay.io/centos/centos:stream8

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Restore pip installed packages.
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          # perfect cache key match

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.playbookdistro }}
